#!/bin/bash

if [ -z "$1" ]; then echo -n "Testen bis: "; read MAX_ZAHL; else MAX_ZAHL=$1; fi

function PRIMTEST {
  P_PRIM=0 # 0 --> Primzahl, != 0 --> keine Primzahl
  P_ZAHL=$1
  if [ $P_ZAHL -le 1 ]; then P_PRIM=1; return $P_PRIM; fi # Zahlen <=1 sind keine Primzahlen
  if [ $(($P_ZAHL % 2)) -eq 0 ] && [ $P_ZAHL -ne 2 ]; then P_PRIM=1; return $P_PRIM; fi # Zahl ist ohne Rest durch 2 teilbar 
											# und ungleich 2
  # teile durch alle ungeraden Zahlen ab 3
  P_MAX=$(echo "scale=0; sqrt($P_ZAHL)" | bc -l)	# Primfaktoren bis Quadratwurzel der Zahl suchen
  for ((p_i=3; p_i<$P_MAX;p_i+=2))
    do
      if [ $(($P_ZAHL % $p_i)) -eq 0 ]; then P_PRIM=1; return $P_PRIM; fi 	# Zahl ohne Rest teilbar 
											# --> keine Primzahl
    done

  return $P_PRIM 
} # end PRIMTEST

n_ZAHL=0
echo -n "2 "
for ((ZAHL=3;ZAHL<$MAX_ZAHL; ZAHL+=2))
  do
    if PRIMTEST $ZAHL # Zahl auf Primzahl testen
      then
        # echo "$ZAHL ist eine Primzahl."
        echo -n "$ZAHL "
	n_ZAHL=$(($n_ZAHL + 1))
      # else
      #  echo "$ZAHL ist KEINE Primzahl."
     fi
done
echo "Es wurden $n_ZAHL Primzahlen gefunden."

exit 0
