#!/bin/bash

if [ -z "$1" ]; then echo -n "Zahl: "; read ZAHL; else ZAHL=$1; fi

function PRIMTEST {
  P_PRIM=0 # 0 --> Primzahl, != 0 --> keine Primzahl
  P_ZAHL=$1
  if [ $P_ZAHL -le 1 ]; then P_PRIM=1; return $P_PRIM; fi # Zahlen <=1 sind keine Primzahlen
  if [ $(($P_ZAHL % 2)) -eq 0 ] && [ $P_ZAHL -ne 2 ]; then P_PRIM=1; return $P_PRIM; fi # Zahl ist ohne Rest durch 2 teilbar 
											# und ungleich 2
  # teile durch alle ungeraden Zahlen ab 3
  for ((p_i=3; p_i<$P_ZAHL;p_i+=2))
    do
      if [ $(($P_ZAHL % $p_i)) -eq 0 ]; then P_PRIM=1; return $P_PRIM; fi 	# Zahl ohne Rest teilbar 
											# --> keine Primzahl
    done

  return $P_PRIM 
} # end PRIMTEST

if PRIMTEST $ZAHL # Zahl auf Primzahl testen
  then
    echo "$ZAHL ist eine Primzahl."
  else
    echo "$ZAHL ist KEINE Primzahl."
 fi

exit 0
