#!/bin/bash

#for i in 1 2 3 4 5 6 7 8 9 10a
#  do
#    echo "$i"
#  done

# nur bash:
for ((i=10; i>=0; i-=2))	# i++ --> Inkrement, i-- --> Dekrement, 
				# i+=2 --> immer um 2 erhöhen, i-=2 --> immer um 2 herunterzählen
  do
    echo -n "$i "
  done

exit 0
